### ISSUE TITLE
QUESTION: How to build when node-sass does not support M1

### ISSUE THREAD

**Issue by kynrai** [joshuapack/beekeeper-studio#1]
**Details:**
How do you build the M1 binary on an M1 when beekeeper requires node-sass which does not support M1

**Version Information [might be relevant to your issue]**
Operating System: OSx Big Sur
App Version [help -> about]: 2.1.1

**Screenshot / GIF [if appropriate]**:
<img width="973" alt="Screenshot 2021-09-15 at 18 42 31" src="https://user-images.githubusercontent.com/8189495/133482961-ad88050d-e892-4196-b5fc-974a02c0bdc6.png">

**Comment by joshuapack** [comment]
Which version of node and yarn are you running?

I have Node v15.11.0 and Yarn v1.22.10

I can send you the binary and you can sign it if need be to try it out.

I was able to run it fine. not sure why. It might be because for node-sass i have it running under rosetta, I may need to test a new environment. Looking into it you'd think I wouldn't be able to build. Unsure as to why my environment is building correctly.

EDIT: it's possible i installed node-sass using something like `npm install --target_arch=x64` however, I don't remember at this time. I would need to clone and try again. Once built, it runs on the Apple silicon

**Comment by joshuapack** [comment]
I will upload binary into release. https://github.com/joshuapack/beekeeper-studio/releases/download/V2.1.1/Beekeeper.Studio.zip

You can try the following on the binary to see if it can be ran:

`sudo xattr -rd com.apple.quarantine /Applications/Beekeeper\ Studio.app`
You may need to self sign it as well: `codesign --force --deep --sign - /Applications/Beekeeper\ Studio.app`

Where `/Applications/Beekeeper\ Studio.app` is the location of the unzipped application.
Let me know if that works.

EDIT: I updated instructions, as I just tested and seemed to work for the binary on my machine.

**Comment by joshuapack** [comment]
@kynrai were you able to get either of them to work? Either your own build or running the binary?

**Comment by kynrai** [comment]
I was not, mac says the binary is damaged, before and after self signing, I tried to rebuild again, same issue. I might get a little further building from a terminal running under rosetta, if that still builds a silicon binary, will try tomorrow morning

**Comment by joshuapack** [comment]
@kynrai did you also try removing the extra apple attribute? After signing?

It's so hard for me to test, since I only have 1 M1 Mac.

**Comment by kynrai** [comment]
@joshuapack sorry for not replying, I had more luck building under a terminal under rosetta emulation and that fixed the issue for me, the binary produced is a silicon binary, thanks!
